// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationEf;

namespace MigrationEf.Migrations
{
    [DbContext(typeof(db))]
    [Migration("20190118112311_in")]
    partial class @in
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MigrationEf.activity", b =>
                {
                    b.Property<int>("activityID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("activityID");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("MigrationEf.course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("MigrationEf.student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("courseID");

                    b.HasKey("ID");

                    b.HasIndex("courseID");

                    b.ToTable("students");
                });

            modelBuilder.Entity("MigrationEf.trip", b =>
                {
                    b.Property<int>("tripID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nAME");

                    b.HasKey("tripID");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("MigrationEf.tripacti", b =>
                {
                    b.Property<int>("tripID");

                    b.Property<int>("activityID");

                    b.HasKey("tripID", "activityID");

                    b.HasIndex("activityID");

                    b.ToTable("tripacti");
                });

            modelBuilder.Entity("MigrationEf.student", b =>
                {
                    b.HasOne("MigrationEf.course", "course")
                        .WithMany("student")
                        .HasForeignKey("courseID");
                });

            modelBuilder.Entity("MigrationEf.tripacti", b =>
                {
                    b.HasOne("MigrationEf.activity", "activity")
                        .WithMany("tripacti")
                        .HasForeignKey("activityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MigrationEf.trip", "trip")
                        .WithMany("tripacti")
                        .HasForeignKey("tripID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
